# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Huawei/Desktop/Python Mini Projects/MarketAutomation/market.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 570)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 570))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 570))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainPage)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(153, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.btnGoPage1 = QtWidgets.QPushButton(self.MainPage)
        self.btnGoPage1.setMinimumSize(QtCore.QSize(350, 50))
        self.btnGoPage1.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.btnGoPage1.setObjectName("btnGoPage1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.btnGoPage1)
        self.btnGoPage2 = QtWidgets.QPushButton(self.MainPage)
        self.btnGoPage2.setMinimumSize(QtCore.QSize(350, 50))
        self.btnGoPage2.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.btnGoPage2.setObjectName("btnGoPage2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btnGoPage2)
        self.btnGoPage3 = QtWidgets.QPushButton(self.MainPage)
        self.btnGoPage3.setMinimumSize(QtCore.QSize(350, 50))
        self.btnGoPage3.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.btnGoPage3.setObjectName("btnGoPage3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btnGoPage3)
        self.btnGoPage4 = QtWidgets.QPushButton(self.MainPage)
        self.btnGoPage4.setMinimumSize(QtCore.QSize(350, 50))
        self.btnGoPage4.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.btnGoPage4.setObjectName("btnGoPage4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btnGoPage4)
        self.btnGoPage5 = QtWidgets.QPushButton(self.MainPage)
        self.btnGoPage5.setMinimumSize(QtCore.QSize(350, 50))
        self.btnGoPage5.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.btnGoPage5.setObjectName("btnGoPage5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.btnGoPage5)
        self.btnGoPage6 = QtWidgets.QPushButton(self.MainPage)
        self.btnGoPage6.setMinimumSize(QtCore.QSize(350, 50))
        self.btnGoPage6.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.btnGoPage6.setObjectName("btnGoPage6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnGoPage6)
        self.btnGoPage8 = QtWidgets.QPushButton(self.MainPage)
        self.btnGoPage8.setMinimumSize(QtCore.QSize(350, 50))
        self.btnGoPage8.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.btnGoPage8.setObjectName("btnGoPage8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnGoPage8)
        self.btnGoPage7 = QtWidgets.QPushButton(self.MainPage)
        self.btnGoPage7.setMinimumSize(QtCore.QSize(350, 50))
        self.btnGoPage7.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.btnGoPage7.setObjectName("btnGoPage7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.btnGoPage7)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.btnCloseCase = QtWidgets.QPushButton(self.MainPage)
        self.btnCloseCase.setMinimumSize(QtCore.QSize(250, 48))
        self.btnCloseCase.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.btnCloseCase.setObjectName("btnCloseCase")
        self.verticalLayout_2.addWidget(self.btnCloseCase)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(152, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.MainPage)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem7)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.btnBrandsProductList_2 = QtWidgets.QPushButton(self.page_2)
        self.btnBrandsProductList_2.setMinimumSize(QtCore.QSize(140, 0))
        self.btnBrandsProductList_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.btnBrandsProductList_2.setObjectName("btnBrandsProductList_2")
        self.verticalLayout_20.addWidget(self.btnBrandsProductList_2)
        self.btnCategoriesProductList_2 = QtWidgets.QPushButton(self.page_2)
        self.btnCategoriesProductList_2.setMinimumSize(QtCore.QSize(140, 0))
        self.btnCategoriesProductList_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnCategoriesProductList_2.setObjectName("btnCategoriesProductList_2")
        self.verticalLayout_20.addWidget(self.btnCategoriesProductList_2)
        self.horizontalLayout_14.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.cmbBrands_4 = QtWidgets.QComboBox(self.page_2)
        self.cmbBrands_4.setMinimumSize(QtCore.QSize(130, 25))
        self.cmbBrands_4.setMaximumSize(QtCore.QSize(130, 16777215))
        self.cmbBrands_4.setObjectName("cmbBrands_4")
        self.verticalLayout_21.addWidget(self.cmbBrands_4)
        self.cmbCategories_5 = QtWidgets.QComboBox(self.page_2)
        self.cmbCategories_5.setMinimumSize(QtCore.QSize(130, 25))
        self.cmbCategories_5.setMaximumSize(QtCore.QSize(130, 16777215))
        self.cmbCategories_5.setObjectName("cmbCategories_5")
        self.verticalLayout_21.addWidget(self.cmbCategories_5)
        self.horizontalLayout_14.addLayout(self.verticalLayout_21)
        self.verticalLayout_19.addLayout(self.horizontalLayout_14)
        self.btnAllProductsList = QtWidgets.QPushButton(self.page_2)
        self.btnAllProductsList.setMinimumSize(QtCore.QSize(140, 0))
        self.btnAllProductsList.setMaximumSize(QtCore.QSize(500, 16777215))
        self.btnAllProductsList.setObjectName("btnAllProductsList")
        self.verticalLayout_19.addWidget(self.btnAllProductsList)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem16)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem17)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setObjectName("label")
        self.horizontalLayout_13.addWidget(self.label)
        self.spnProductId = QtWidgets.QSpinBox(self.page_2)
        self.spnProductId.setMinimumSize(QtCore.QSize(100, 25))
        self.spnProductId.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spnProductId.setMaximum(10000)
        self.spnProductId.setObjectName("spnProductId")
        self.horizontalLayout_13.addWidget(self.spnProductId)
        self.label_11 = QtWidgets.QLabel(self.page_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.spnProductStock = QtWidgets.QSpinBox(self.page_2)
        self.spnProductStock.setMinimumSize(QtCore.QSize(100, 25))
        self.spnProductStock.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spnProductStock.setMaximum(10000)
        self.spnProductStock.setObjectName("spnProductStock")
        self.horizontalLayout_13.addWidget(self.spnProductStock)
        self.verticalLayout_19.addLayout(self.horizontalLayout_13)
        self.btnBasketInAddProduct = QtWidgets.QPushButton(self.page_2)
        self.btnBasketInAddProduct.setObjectName("btnBasketInAddProduct")
        self.verticalLayout_19.addWidget(self.btnBasketInAddProduct)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem18)
        self.btnSell = QtWidgets.QPushButton(self.page_2)
        self.btnSell.setMinimumSize(QtCore.QSize(100, 0))
        self.btnSell.setMaximumSize(QtCore.QSize(500, 16777215))
        self.btnSell.setObjectName("btnSell")
        self.verticalLayout_19.addWidget(self.btnSell)
        self.btnDeleteBasket = QtWidgets.QPushButton(self.page_2)
        self.btnDeleteBasket.setMinimumSize(QtCore.QSize(100, 0))
        self.btnDeleteBasket.setMaximumSize(QtCore.QSize(500, 16777215))
        self.btnDeleteBasket.setObjectName("btnDeleteBasket")
        self.verticalLayout_19.addWidget(self.btnDeleteBasket)
        self.btnGoMenu_6 = QtWidgets.QPushButton(self.page_2)
        self.btnGoMenu_6.setMinimumSize(QtCore.QSize(100, 0))
        self.btnGoMenu_6.setMaximumSize(QtCore.QSize(500, 16777215))
        self.btnGoMenu_6.setObjectName("btnGoMenu_6")
        self.verticalLayout_19.addWidget(self.btnGoMenu_6)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem19)
        self.horizontalLayout_15.addLayout(self.verticalLayout_19)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem20)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_22.addWidget(self.label_10)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_4.setMinimumSize(QtCore.QSize(600, 200))
        self.tableWidget_4.setMaximumSize(QtCore.QSize(500, 200))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.verticalLayout_22.addWidget(self.tableWidget_4)
        self.verticalLayout_18.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_23.addWidget(self.label_5)
        self.tblBasketList = QtWidgets.QTableWidget(self.page_2)
        self.tblBasketList.setMinimumSize(QtCore.QSize(600, 200))
        self.tblBasketList.setMaximumSize(QtCore.QSize(500, 200))
        self.tblBasketList.setObjectName("tblBasketList")
        self.tblBasketList.setColumnCount(0)
        self.tblBasketList.setRowCount(0)
        self.verticalLayout_23.addWidget(self.tblBasketList)
        self.verticalLayout_18.addLayout(self.verticalLayout_23)
        self.horizontalLayout_15.addLayout(self.verticalLayout_18)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem21)
        self.stackedWidget.addWidget(self.page_2)
        self.AddProductPage = QtWidgets.QWidget()
        self.AddProductPage.setObjectName("AddProductPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.AddProductPage)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem22)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.AddProductPage)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.AddProductPage)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.AddProductPage)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.AddProductPage)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.AddProductPage)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.AddProductPage)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.AddProductPage)
        self.label_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lneProductName = QtWidgets.QLineEdit(self.AddProductPage)
        self.lneProductName.setMinimumSize(QtCore.QSize(200, 25))
        self.lneProductName.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lneProductName.setObjectName("lneProductName")
        self.verticalLayout_4.addWidget(self.lneProductName)
        self.spnStock = QtWidgets.QSpinBox(self.AddProductPage)
        self.spnStock.setMinimumSize(QtCore.QSize(200, 25))
        self.spnStock.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spnStock.setMaximum(10000)
        self.spnStock.setObjectName("spnStock")
        self.verticalLayout_4.addWidget(self.spnStock)
        self.spnPrice = QtWidgets.QDoubleSpinBox(self.AddProductPage)
        self.spnPrice.setMinimumSize(QtCore.QSize(200, 25))
        self.spnPrice.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spnPrice.setMaximum(10000.0)
        self.spnPrice.setObjectName("spnPrice")
        self.verticalLayout_4.addWidget(self.spnPrice)
        self.cmbBrands = QtWidgets.QComboBox(self.AddProductPage)
        self.cmbBrands.setMinimumSize(QtCore.QSize(200, 25))
        self.cmbBrands.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbBrands.setObjectName("cmbBrands")
        self.verticalLayout_4.addWidget(self.cmbBrands)
        self.cmbCategories = QtWidgets.QComboBox(self.AddProductPage)
        self.cmbCategories.setMinimumSize(QtCore.QSize(200, 25))
        self.cmbCategories.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbCategories.setObjectName("cmbCategories")
        self.verticalLayout_4.addWidget(self.cmbCategories)
        self.dateEditStt = QtWidgets.QDateEdit(self.AddProductPage)
        self.dateEditStt.setMinimumSize(QtCore.QSize(200, 25))
        self.dateEditStt.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dateEditStt.setObjectName("dateEditStt")
        self.verticalLayout_4.addWidget(self.dateEditStt)
        self.spnId = QtWidgets.QSpinBox(self.AddProductPage)
        self.spnId.setMinimumSize(QtCore.QSize(200, 25))
        self.spnId.setMaximumSize(QtCore.QSize(200, 16777215))
        self.spnId.setMaximum(10000)
        self.spnId.setObjectName("spnId")
        self.verticalLayout_4.addWidget(self.spnId)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.lblStatMessage = QtWidgets.QLabel(self.AddProductPage)
        self.lblStatMessage.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lblStatMessage.setText("")
        self.lblStatMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStatMessage.setObjectName("lblStatMessage")
        self.verticalLayout_5.addWidget(self.lblStatMessage)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem23)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.AddProductPage)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(722, 0))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableWidget_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnAddProduct = QtWidgets.QPushButton(self.AddProductPage)
        self.btnAddProduct.setMinimumSize(QtCore.QSize(150, 0))
        self.btnAddProduct.setObjectName("btnAddProduct")
        self.horizontalLayout_5.addWidget(self.btnAddProduct)
        self.btnUpdateProduct = QtWidgets.QPushButton(self.AddProductPage)
        self.btnUpdateProduct.setMinimumSize(QtCore.QSize(150, 0))
        self.btnUpdateProduct.setObjectName("btnUpdateProduct")
        self.horizontalLayout_5.addWidget(self.btnUpdateProduct)
        self.btnGoMenu = QtWidgets.QPushButton(self.AddProductPage)
        self.btnGoMenu.setMinimumSize(QtCore.QSize(150, 0))
        self.btnGoMenu.setObjectName("btnGoMenu")
        self.horizontalLayout_5.addWidget(self.btnGoMenu)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.AddProductPage)
        self.DeleteProductPage = QtWidgets.QWidget()
        self.DeleteProductPage.setObjectName("DeleteProductPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.DeleteProductPage)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem24)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem25)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem26)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem27)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btnBrandsProductList = QtWidgets.QPushButton(self.DeleteProductPage)
        self.btnBrandsProductList.setMinimumSize(QtCore.QSize(100, 0))
        self.btnBrandsProductList.setObjectName("btnBrandsProductList")
        self.verticalLayout_11.addWidget(self.btnBrandsProductList)
        self.btnCategoriesProductList = QtWidgets.QPushButton(self.DeleteProductPage)
        self.btnCategoriesProductList.setMinimumSize(QtCore.QSize(100, 0))
        self.btnCategoriesProductList.setObjectName("btnCategoriesProductList")
        self.verticalLayout_11.addWidget(self.btnCategoriesProductList)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.cmbBrands_3 = QtWidgets.QComboBox(self.DeleteProductPage)
        self.cmbBrands_3.setMinimumSize(QtCore.QSize(150, 25))
        self.cmbBrands_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbBrands_3.setObjectName("cmbBrands_3")
        self.verticalLayout_12.addWidget(self.cmbBrands_3)
        self.cmbCategories_3 = QtWidgets.QComboBox(self.DeleteProductPage)
        self.cmbCategories_3.setMinimumSize(QtCore.QSize(150, 25))
        self.cmbCategories_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbCategories_3.setObjectName("cmbCategories_3")
        self.verticalLayout_12.addWidget(self.cmbCategories_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem28)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btnDeleteBrands = QtWidgets.QPushButton(self.DeleteProductPage)
        self.btnDeleteBrands.setMinimumSize(QtCore.QSize(100, 0))
        self.btnDeleteBrands.setObjectName("btnDeleteBrands")
        self.verticalLayout_7.addWidget(self.btnDeleteBrands)
        self.btnDeleteCategories = QtWidgets.QPushButton(self.DeleteProductPage)
        self.btnDeleteCategories.setMinimumSize(QtCore.QSize(100, 0))
        self.btnDeleteCategories.setObjectName("btnDeleteCategories")
        self.verticalLayout_7.addWidget(self.btnDeleteCategories)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cmbBrands_2 = QtWidgets.QComboBox(self.DeleteProductPage)
        self.cmbBrands_2.setMinimumSize(QtCore.QSize(150, 25))
        self.cmbBrands_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbBrands_2.setObjectName("cmbBrands_2")
        self.verticalLayout_8.addWidget(self.cmbBrands_2)
        self.cmbCategories_4 = QtWidgets.QComboBox(self.DeleteProductPage)
        self.cmbCategories_4.setMinimumSize(QtCore.QSize(150, 25))
        self.cmbCategories_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbCategories_4.setObjectName("cmbCategories_4")
        self.verticalLayout_8.addWidget(self.cmbCategories_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem29)
        self.btnDeleteStt = QtWidgets.QPushButton(self.DeleteProductPage)
        self.btnDeleteStt.setMinimumSize(QtCore.QSize(150, 30))
        self.btnDeleteStt.setObjectName("btnDeleteStt")
        self.verticalLayout_9.addWidget(self.btnDeleteStt)
        self.btnProductDelete = QtWidgets.QPushButton(self.DeleteProductPage)
        self.btnProductDelete.setMinimumSize(QtCore.QSize(0, 30))
        self.btnProductDelete.setObjectName("btnProductDelete")
        self.verticalLayout_9.addWidget(self.btnProductDelete)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem30)
        self.lblStatMessage_2 = QtWidgets.QLabel(self.DeleteProductPage)
        self.lblStatMessage_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lblStatMessage_2.setText("")
        self.lblStatMessage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStatMessage_2.setObjectName("lblStatMessage_2")
        self.verticalLayout_9.addWidget(self.lblStatMessage_2)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem31)
        self.btnGoMenu_2 = QtWidgets.QPushButton(self.DeleteProductPage)
        self.btnGoMenu_2.setMinimumSize(QtCore.QSize(150, 0))
        self.btnGoMenu_2.setObjectName("btnGoMenu_2")
        self.verticalLayout_9.addWidget(self.btnGoMenu_2)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem32)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem33)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.tableWidget = QtWidgets.QTableWidget(self.DeleteProductPage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.tableWidget)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.stackedWidget.addWidget(self.DeleteProductPage)
        self.ProductsTablePage = QtWidgets.QWidget()
        self.ProductsTablePage.setObjectName("ProductsTablePage")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.ProductsTablePage)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem34)
        self.btnFiltersBrandProducts = QtWidgets.QPushButton(self.ProductsTablePage)
        self.btnFiltersBrandProducts.setMinimumSize(QtCore.QSize(140, 0))
        self.btnFiltersBrandProducts.setObjectName("btnFiltersBrandProducts")
        self.horizontalLayout_8.addWidget(self.btnFiltersBrandProducts)
        self.cmbBrands_6 = QtWidgets.QComboBox(self.ProductsTablePage)
        self.cmbBrands_6.setMinimumSize(QtCore.QSize(150, 25))
        self.cmbBrands_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbBrands_6.setObjectName("cmbBrands_6")
        self.cmbBrands_6.addItem("")
        self.cmbBrands_6.addItem("")
        self.cmbBrands_6.addItem("")
        self.cmbBrands_6.addItem("")
        self.cmbBrands_6.addItem("")
        self.cmbBrands_6.addItem("")
        self.cmbBrands_6.addItem("")
        self.horizontalLayout_8.addWidget(self.cmbBrands_6)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem35)
        self.btnFiltersCategoryProducts = QtWidgets.QPushButton(self.ProductsTablePage)
        self.btnFiltersCategoryProducts.setMinimumSize(QtCore.QSize(140, 0))
        self.btnFiltersCategoryProducts.setObjectName("btnFiltersCategoryProducts")
        self.horizontalLayout_8.addWidget(self.btnFiltersCategoryProducts)
        self.cmbCategories_2 = QtWidgets.QComboBox(self.ProductsTablePage)
        self.cmbCategories_2.setMinimumSize(QtCore.QSize(150, 25))
        self.cmbCategories_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cmbCategories_2.setObjectName("cmbCategories_2")
        self.cmbCategories_2.addItem("")
        self.cmbCategories_2.addItem("")
        self.cmbCategories_2.addItem("")
        self.cmbCategories_2.addItem("")
        self.cmbCategories_2.addItem("")
        self.cmbCategories_2.addItem("")
        self.cmbCategories_2.addItem("")
        self.horizontalLayout_8.addWidget(self.cmbCategories_2)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem36)
        self.btnAllProducts = QtWidgets.QPushButton(self.ProductsTablePage)
        self.btnAllProducts.setMinimumSize(QtCore.QSize(140, 0))
        self.btnAllProducts.setObjectName("btnAllProducts")
        self.horizontalLayout_8.addWidget(self.btnAllProducts)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem37)
        self.btnGoMenu_3 = QtWidgets.QPushButton(self.ProductsTablePage)
        self.btnGoMenu_3.setMinimumSize(QtCore.QSize(140, 0))
        self.btnGoMenu_3.setObjectName("btnGoMenu_3")
        self.horizontalLayout_8.addWidget(self.btnGoMenu_3)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem38)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.ProductsTablePage)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.verticalLayout_13.addWidget(self.tableWidget_3)
        self.lblStock = QtWidgets.QLabel(self.ProductsTablePage)
        self.lblStock.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStock.setObjectName("lblStock")
        self.verticalLayout_13.addWidget(self.lblStock)
        self.stackedWidget.addWidget(self.ProductsTablePage)
        self.BrandsPage = QtWidgets.QWidget()
        self.BrandsPage.setObjectName("BrandsPage")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.BrandsPage)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem39)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem40)
        self.BrandsList = QtWidgets.QListWidget(self.BrandsPage)
        self.BrandsList.setMinimumSize(QtCore.QSize(0, 300))
        self.BrandsList.setObjectName("BrandsList")
        self.verticalLayout_14.addWidget(self.BrandsList)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lneBrandName = QtWidgets.QLineEdit(self.BrandsPage)
        self.lneBrandName.setMinimumSize(QtCore.QSize(200, 25))
        self.lneBrandName.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lneBrandName.setObjectName("lneBrandName")
        self.horizontalLayout_9.addWidget(self.lneBrandName)
        self.btnAddBrand = QtWidgets.QPushButton(self.BrandsPage)
        self.btnAddBrand.setMinimumSize(QtCore.QSize(140, 0))
        self.btnAddBrand.setObjectName("btnAddBrand")
        self.horizontalLayout_9.addWidget(self.btnAddBrand)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.lblBrandStatMessage = QtWidgets.QLabel(self.BrandsPage)
        self.lblBrandStatMessage.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lblBrandStatMessage.setText("")
        self.lblBrandStatMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBrandStatMessage.setObjectName("lblBrandStatMessage")
        self.verticalLayout_14.addWidget(self.lblBrandStatMessage)
        self.btnDeleteBrand = QtWidgets.QPushButton(self.BrandsPage)
        self.btnDeleteBrand.setMinimumSize(QtCore.QSize(0, 30))
        self.btnDeleteBrand.setObjectName("btnDeleteBrand")
        self.verticalLayout_14.addWidget(self.btnDeleteBrand)
        self.btnGoMenu_4 = QtWidgets.QPushButton(self.BrandsPage)
        self.btnGoMenu_4.setMinimumSize(QtCore.QSize(150, 0))
        self.btnGoMenu_4.setObjectName("btnGoMenu_4")
        self.verticalLayout_14.addWidget(self.btnGoMenu_4)
        spacerItem41 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem41)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem42)
        self.verticalLayout_15.addLayout(self.horizontalLayout_10)
        self.stackedWidget.addWidget(self.BrandsPage)
        self.CategoriesPage = QtWidgets.QWidget()
        self.CategoriesPage.setObjectName("CategoriesPage")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.CategoriesPage)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem43)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem44)
        self.CategoryList = QtWidgets.QListWidget(self.CategoriesPage)
        self.CategoryList.setMinimumSize(QtCore.QSize(0, 300))
        self.CategoryList.setObjectName("CategoryList")
        self.verticalLayout_16.addWidget(self.CategoryList)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lneCategoryName = QtWidgets.QLineEdit(self.CategoriesPage)
        self.lneCategoryName.setMinimumSize(QtCore.QSize(200, 25))
        self.lneCategoryName.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lneCategoryName.setObjectName("lneCategoryName")
        self.horizontalLayout_12.addWidget(self.lneCategoryName)
        self.btnAddCategory = QtWidgets.QPushButton(self.CategoriesPage)
        self.btnAddCategory.setMinimumSize(QtCore.QSize(140, 0))
        self.btnAddCategory.setObjectName("btnAddCategory")
        self.horizontalLayout_12.addWidget(self.btnAddCategory)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.lblCategoryStatMessage = QtWidgets.QLabel(self.CategoriesPage)
        self.lblCategoryStatMessage.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lblCategoryStatMessage.setText("")
        self.lblCategoryStatMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCategoryStatMessage.setObjectName("lblCategoryStatMessage")
        self.verticalLayout_16.addWidget(self.lblCategoryStatMessage)
        self.btnDeleteCategory = QtWidgets.QPushButton(self.CategoriesPage)
        self.btnDeleteCategory.setMinimumSize(QtCore.QSize(0, 30))
        self.btnDeleteCategory.setObjectName("btnDeleteCategory")
        self.verticalLayout_16.addWidget(self.btnDeleteCategory)
        self.btnGoMenu_5 = QtWidgets.QPushButton(self.CategoriesPage)
        self.btnGoMenu_5.setMinimumSize(QtCore.QSize(150, 0))
        self.btnGoMenu_5.setObjectName("btnGoMenu_5")
        self.verticalLayout_16.addWidget(self.btnGoMenu_5)
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem45)
        self.horizontalLayout_11.addLayout(self.verticalLayout_16)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem46)
        self.verticalLayout_17.addLayout(self.horizontalLayout_11)
        self.stackedWidget.addWidget(self.CategoriesPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.cmbBrands_4.setCurrentIndex(-1)
        self.cmbCategories_5.setCurrentIndex(-1)
        self.cmbBrands.setCurrentIndex(-1)
        self.cmbCategories.setCurrentIndex(-1)
        self.cmbBrands_3.setCurrentIndex(-1)
        self.cmbCategories_3.setCurrentIndex(-1)
        self.cmbBrands_2.setCurrentIndex(-1)
        self.cmbCategories_4.setCurrentIndex(-1)
        self.cmbBrands_6.setCurrentIndex(-1)
        self.cmbCategories_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnGoPage1.setText(_translate("MainWindow", "Satış Yap"))
        self.btnGoPage2.setText(_translate("MainWindow", "Ürün Ekle/Güncelle"))
        self.btnGoPage3.setText(_translate("MainWindow", "Ürün Sil"))
        self.btnGoPage4.setText(_translate("MainWindow", "Ürünler"))
        self.btnGoPage5.setText(_translate("MainWindow", "Markalar"))
        self.btnGoPage6.setText(_translate("MainWindow", "Kategoriler"))
        self.btnGoPage8.setText(_translate("MainWindow", "Satış Geçmişi"))
        self.btnGoPage7.setText(_translate("MainWindow", "Ciro"))
        self.btnCloseCase.setText(_translate("MainWindow", "Kasayı Kapat"))
        self.btnBrandsProductList_2.setText(_translate("MainWindow", "Markaya Göre Listele"))
        self.btnCategoriesProductList_2.setText(_translate("MainWindow", "Kategoriye Göre Listele"))
        self.btnAllProductsList.setText(_translate("MainWindow", "Tüm ürünleri Listele"))
        self.label.setText(_translate("MainWindow", "Ürün İd"))
        self.label_11.setText(_translate("MainWindow", "Adet"))
        self.btnBasketInAddProduct.setText(_translate("MainWindow", "Sepete Ekle"))
        self.btnSell.setText(_translate("MainWindow", "Satış"))
        self.btnDeleteBasket.setText(_translate("MainWindow", "Sepeti Temizle"))
        self.btnGoMenu_6.setText(_translate("MainWindow", "Menü"))
        self.label_10.setText(_translate("MainWindow", "Ürünler"))
        self.label_5.setText(_translate("MainWindow", "Sepet"))
        self.label_2.setText(_translate("MainWindow", "Ürün Adı :"))
        self.label_4.setText(_translate("MainWindow", "Stok Miktarı : "))
        self.label_3.setText(_translate("MainWindow", "Birim Fiyatı : "))
        self.label_6.setText(_translate("MainWindow", "Marka :"))
        self.label_7.setText(_translate("MainWindow", "Kategori :"))
        self.label_8.setText(_translate("MainWindow", "Sttt : "))
        self.label_9.setText(_translate("MainWindow", "İd : "))
        self.btnAddProduct.setText(_translate("MainWindow", " Ekle"))
        self.btnUpdateProduct.setText(_translate("MainWindow", "Güncelle"))
        self.btnGoMenu.setText(_translate("MainWindow", "Menü"))
        self.btnBrandsProductList.setText(_translate("MainWindow", "Markaya Göre Listele"))
        self.btnCategoriesProductList.setText(_translate("MainWindow", "Kategoriye Göre Listele"))
        self.btnDeleteBrands.setText(_translate("MainWindow", "Markaya Göre Sil"))
        self.btnDeleteCategories.setText(_translate("MainWindow", "Kategoriye Göre Sil"))
        self.btnDeleteStt.setText(_translate("MainWindow", "Son Tüketim Tarihi Geçenleri Sil"))
        self.btnProductDelete.setText(_translate("MainWindow", "Seçilen Ürünü Sil"))
        self.btnGoMenu_2.setText(_translate("MainWindow", "Menü"))
        self.btnFiltersBrandProducts.setText(_translate("MainWindow", "Markaya Göre Listele"))
        self.cmbBrands_6.setItemText(0, _translate("MainWindow", "Huawei"))
        self.cmbBrands_6.setItemText(1, _translate("MainWindow", "Acer"))
        self.cmbBrands_6.setItemText(2, _translate("MainWindow", "Samsung"))
        self.cmbBrands_6.setItemText(3, _translate("MainWindow", "Apple"))
        self.cmbBrands_6.setItemText(4, _translate("MainWindow", "Xiaomi"))
        self.cmbBrands_6.setItemText(5, _translate("MainWindow", "Vestel"))
        self.cmbBrands_6.setItemText(6, _translate("MainWindow", "Oppo"))
        self.btnFiltersCategoryProducts.setText(_translate("MainWindow", "Kategoriye Göre Listele"))
        self.cmbCategories_2.setItemText(0, _translate("MainWindow", "Huawei"))
        self.cmbCategories_2.setItemText(1, _translate("MainWindow", "Acer"))
        self.cmbCategories_2.setItemText(2, _translate("MainWindow", "Samsung"))
        self.cmbCategories_2.setItemText(3, _translate("MainWindow", "Apple"))
        self.cmbCategories_2.setItemText(4, _translate("MainWindow", "Xiaomi"))
        self.cmbCategories_2.setItemText(5, _translate("MainWindow", "Vestel"))
        self.cmbCategories_2.setItemText(6, _translate("MainWindow", "Oppo"))
        self.btnAllProducts.setText(_translate("MainWindow", "Tüm Ürünler"))
        self.btnGoMenu_3.setText(_translate("MainWindow", "Menü"))
        self.lblStock.setText(_translate("MainWindow", "Toplam Stok : "))
        self.btnAddBrand.setText(_translate("MainWindow", "Ekle"))
        self.btnDeleteBrand.setText(_translate("MainWindow", "Seçilen Markayı Sil"))
        self.btnGoMenu_4.setText(_translate("MainWindow", "Menü"))
        self.btnAddCategory.setText(_translate("MainWindow", "Ekle"))
        self.btnDeleteCategory.setText(_translate("MainWindow", "Seçilen Kategoriyi Sil"))
        self.btnGoMenu_5.setText(_translate("MainWindow", "Menü"))

